publish gems to github; add badges to README.md
voxpupuli/voxpupuli-test pull request #43
Opened 2021-07-13 08:00 UTC by bastelfreak

2021-07-13 08:05 UTC, ekohl requested changes

2021-07-13 08:05 UTC, ekohl commented on README.md
> +[![RubyGem Downloads](https://img.shields.io/gem/dt/voxpupui-test.svg)](https://rubygems.org/gems/voxpupui-test)
voxpupui -> voxpupuli

2021-07-13 08:05 UTC, ekohl commented on voxpupuli-test.gemspec
> +  s.add_development_dependency 'codecov'
Can we make this a group in `Gemfile` and only include conditionally?

2021-07-13 08:05 UTC, ekohl commented on .github/workflows/test.yml
> +          BUNDLE_WITHOUT: release
Why is this needed? On line 7/8 it's already set.

2021-07-13 08:21 UTC, ekohl approved these changes

2021-07-13 08:24 UTC, llowder approved these changes

2021-07-13 08:39 UTC, ekohl commented on spec/spec_helper.rb
> +end
```suggestion
begin
  require 'simplecov'
  require 'simplecov-console'
  require 'codecov'
rescue LoadError
else
  SimpleCov.start do
    track_files 'lib/**/*.rb'

    add_filter '/spec'

    enable_coverage :branch

    # do not track vendored files
    add_filter '/vendor'
    add_filter '/.vendor'
  end

  SimpleCov.formatters = [
    SimpleCov::Formatter::Console,
    SimpleCov::Formatter::Codecov,
  ]
end
```

2021-07-13 08:39 UTC, ekohl commented on Gemfile
> +group :coverage do
On IRC I suggested to make it optional:
```suggestion
group :coverage, optional: !ENV['COVERAGE'] do
```

2021-07-13 08:44 UTC, ekohl commented on .github/workflows/test.yml
> +          COVERAGE: ${{ matrix.coverage }}
I think you need to set this at a higher level or at least duplicate it for the installation step

2021-07-20 16:06 UTC, sebastianrakel approved these changes

2021-07-21 09:21 UTC, merged