Depend on puppet-lint >= 2.5.0
voxpupuli/voxpupuli-test pull request #45
Opened 2021-07-26 12:31 UTC by bastelfreak

puppet-lint is required for Ruby 3 support.

2021-07-26 12:32 UTC, TuningYourCode approved these changes

2021-07-26 12:51 UTC, ekohl requested changes

2021-07-26 12:51 UTC, ekohl commented on voxpupuli-test.gemspec
> +  s.add_runtime_dependency 'puppet-lint', '>= 2.5.0'
I think Rubocop wants dependencies sorted. Or at least, newer ones do so let's start with that. I'd also prefer to add it in the `# Linting` section.

2021-07-27 08:07 UTC, bastelfreak commented on voxpupuli-test.gemspec
> +  s.add_runtime_dependency 'puppet-lint', '>= 2.5.0'
fixed it

2021-07-27 12:13 UTC, ekohl approved these changes
I guess it doesn't hurt to explicitly depend on puppet-lint rather than implicitly.

2021-07-27 12:43 UTC, merged